"""
Unit Tests for TechnicalIndicatorService
測試範圍: TR-TC-001 ~ TR-TC-004
Status: ✅ Generated by Sentinel
"""
import pytest
import pandas as pd
import numpy as np
from backend.apps.core.services.technical_indicators import TechnicalIndicatorService


class TestMovingAverage:
    """測試移動平均線計算 - TC-001"""
    
    def test_calculate_ma_normal_case(self):
        """TC-001-01: 正常情況 - 5/10/20日均線計算正確"""
        # Arrange
        data = [
            {"date": f"2024-01-{i:02d}", "close": 100.0 + i}
            for i in range(1, 61)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_ma(data, periods=[5, 10, 20])
        
        # Assert
        assert "ma5" in result
        assert "ma10" in result
        assert "ma20" in result
        assert len(result["ma5"]) == 60
        
        # 前4個值應該是 None (不足5天)
        assert result["ma5"][:4] == [None, None, None, None]
        
        # 第5個值應該是前5天的平均 (101+102+103+104+105)/5 = 103.0
        assert result["ma5"][4] == pytest.approx(103.0, rel=1e-5)
    
    def test_calculate_ma_insufficient_data(self):
        """TC-001-02: 邊界條件 - 數據點少於週期數"""
        # Arrange: 只有3筆數據，但要求計算5日均線
        data = [
            {"date": "2024-01-01", "close": 100.0},
            {"date": "2024-01-02", "close": 102.0},
            {"date": "2024-01-03", "close": 104.0},
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_ma(data, periods=[5])
        
        # Assert
        assert result["ma5"] == [None, None, None]  # 全部是 None
    
    def test_calculate_ma_empty_array(self):
        """TC-001-03: 邊界條件 - 空陣列"""
        # Arrange
        data = []
        
        # Act
        result = TechnicalIndicatorService.calculate_ma(data, periods=[5, 10])
        
        # Assert
        assert result == {"ma5": [], "ma10": []}
    
    def test_calculate_ma_missing_close_column(self):
        """TC-001-04: 錯誤處理 - 缺少 close 欄位"""
        # Arrange
        data = [
            {"date": "2024-01-01", "open": 100.0},  # 沒有 close
            {"date": "2024-01-02", "open": 102.0},
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_ma(data, periods=[5])
        
        # Assert
        assert result == {"ma5": []}
    
    def test_calculate_ma_with_none_values(self):
        """TC-001-05: 邊界條件 - 數據中包含 None"""
        # Arrange
        data = [
            {"date": "2024-01-01", "close": 100.0},
            {"date": "2024-01-02", "close": None},
            {"date": "2024-01-03", "close": 102.0},
            {"date": "2024-01-04", "close": 104.0},
            {"date": "2024-01-05", "close": 106.0},
            {"date": "2024-01-06", "close": 108.0},
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_ma(data, periods=[3])
        
        # Assert
        # Pandas 會跳過 None，但會造成計算結果異常
        assert len(result["ma3"]) == 6


class TestMACD:
    """測試 MACD 指標計算 - TC-002"""
    
    def test_calculate_macd_normal_case(self):
        """TC-002-01: 正常情況 - MACD 計算正確"""
        # Arrange: 至少需要 26 + 9 = 35 天數據
        data = [
            {"date": f"2024-01-{i:02d}" if i < 32 else f"2024-02-{i-31:02d}", 
             "close": 100.0 + i * 0.5}
            for i in range(1, 41)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_macd(data)
        
        # Assert
        assert "macd" in result
        assert "signal" in result
        assert "histogram" in result
        assert len(result["macd"]) == 40
        assert len(result["signal"]) == 40
        assert len(result["histogram"]) == 40
    
    def test_calculate_macd_insufficient_data(self):
        """TC-002-02: 邊界條件 - 數據不足 26 天"""
        # Arrange: 只有 20 天
        data = [
            {"date": f"2024-01-{i:02d}", "close": 100.0 + i}
            for i in range(1, 21)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_macd(data)
        
        # Assert
        # 前面的值會是 None，但仍會計算 EMA
        assert len(result["macd"]) == 20
        assert len(result["signal"]) == 20
    
    def test_calculate_macd_empty_data(self):
        """TC-002-03: 邊界條件 - 空數據"""
        # Arrange
        data = []
        
        # Act
        result = TechnicalIndicatorService.calculate_macd(data)
        
        # Assert
        assert result == {"macd": [], "signal": [], "histogram": []}
    
    def test_calculate_macd_custom_parameters(self):
        """TC-002-04: 自定義參數 - 快線/慢線/訊號線"""
        # Arrange
        data = [
            {"date": f"2024-01-{i:02d}" if i < 32 else f"2024-02-{i-31:02d}", 
             "close": 100.0 + i}
            for i in range(1, 41)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_macd(
            data, fast=6, slow=13, signal=5
        )
        
        # Assert
        assert len(result["macd"]) == 40
        assert len(result["signal"]) == 40


class TestRSI:
    """測試 RSI 指標計算 - TC-003"""
    
    def test_calculate_rsi_normal_case(self):
        """TC-003-01: 正常情況 - 14日 RSI 計算正確"""
        # Arrange: 至少 15 天 (第一天用於計算差值)
        data = [
            {"date": f"2024-01-{i:02d}", "close": 100.0 + i}
            for i in range(1, 31)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_rsi(data, period=14)
        
        # Assert
        assert len(result) == 30
        # 前面會有 None，因為需要足夠數據
        assert result[0] is None
        
        # RSI 應在 0-100 之間
        valid_rsi = [x for x in result if x is not None]
        assert all(0 <= x <= 100 for x in valid_rsi)
    
    def test_calculate_rsi_all_rising(self):
        """TC-003-02: 極端值 - 全部上漲 (RSI → 100)"""
        # Arrange: 持續上漲
        data = [
            {"date": f"2024-01-{i:02d}", "close": 100.0 + i * 10}
            for i in range(1, 31)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_rsi(data, period=14)
        
        # Assert
        valid_rsi = [x for x in result if x is not None and not np.isnan(x)]
        # 持續上漲，RSI 應該接近 100
        if valid_rsi:
            assert max(valid_rsi) > 90
    
    def test_calculate_rsi_all_falling(self):
        """TC-003-03: 極端值 - 全部下跌 (RSI → 0)"""
        # Arrange: 持續下跌
        data = [
            {"date": f"2024-01-{i:02d}", "close": 200.0 - i * 10}
            for i in range(1, 31)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_rsi(data, period=14)
        
        # Assert
        valid_rsi = [x for x in result if x is not None and not np.isnan(x)]
        # 持續下跌，RSI 應該接近 0
        if valid_rsi:
            assert min(valid_rsi) < 10
    
    def test_calculate_rsi_insufficient_data(self):
        """TC-003-04: 邊界條件 - 數據點少於 14 天"""
        # Arrange
        data = [
            {"date": f"2024-01-{i:02d}", "close": 100.0 + i}
            for i in range(1, 10)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_rsi(data, period=14)
        
        # Assert
        assert len(result) == 9
        # 所有值應該都是 None
        assert all(x is None for x in result)
    
    def test_calculate_rsi_empty_data(self):
        """TC-003-05: 邊界條件 - 空數據"""
        # Arrange
        data = []
        
        # Act
        result = TechnicalIndicatorService.calculate_rsi(data)
        
        # Assert
        assert result == []


class TestKDJ:
    """測試 KDJ 指標計算 - TC-004"""
    
    def test_calculate_kdj_normal_case(self):
        """TC-004-01: 正常情況 - K/D/J 計算正確"""
        # Arrange
        data = [
            {
                "date": f"2024-01-{i:02d}",
                "high": 105.0 + i,
                "low": 95.0 + i,
                "close": 100.0 + i
            }
            for i in range(1, 31)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_kdj(data, k_period=9, d_period=3)
        
        # Assert
        assert "k" in result
        assert "d" in result
        assert "j" in result
        assert len(result["k"]) == 30
        assert len(result["d"]) == 30
        assert len(result["j"]) == 30
        
        # K, D, J 應該在合理範圍內 (通常 0-100，但 J 可能超出)
        valid_k = [x for x in result["k"] if x is not None]
        valid_d = [x for x in result["d"] if x is not None]
        assert all(0 <= x <= 100 for x in valid_k)
        assert all(0 <= x <= 100 for x in valid_d)
    
    def test_calculate_kdj_missing_columns(self):
        """TC-004-02: 錯誤處理 - 缺少必要欄位"""
        # Arrange: 只有 close，缺少 high 和 low
        data = [
            {"date": "2024-01-01", "close": 100.0},
            {"date": "2024-01-02", "close": 102.0},
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_kdj(data)
        
        # Assert
        assert result == {"k": [], "d": [], "j": []}
    
    def test_calculate_kdj_insufficient_data(self):
        """TC-004-03: 邊界條件 - 數據不足 9 天"""
        # Arrange
        data = [
            {
                "date": f"2024-01-0{i}",
                "high": 105.0 + i,
                "low": 95.0 + i,
                "close": 100.0 + i
            }
            for i in range(1, 6)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_kdj(data, k_period=9)
        
        # Assert
        assert len(result["k"]) == 5
        # 前面的值會是 None
    
    def test_calculate_kdj_empty_data(self):
        """TC-004-04: 邊界條件 - 空數據"""
        # Arrange
        data = []
        
        # Act
        result = TechnicalIndicatorService.calculate_kdj(data)
        
        # Assert
        assert result == {"k": [], "d": [], "j": []}


class TestAllIndicators:
    """測試綜合指標計算 - TC-005"""
    
    def test_calculate_all_indicators(self):
        """TC-005-01: 一次性計算所有指標"""
        # Arrange
        data = [
            {
                "date": f"2024-01-{i:02d}" if i < 32 else f"2024-02-{i-31:02d}",
                "open": 98.0 + i,
                "high": 105.0 + i,
                "low": 95.0 + i,
                "close": 100.0 + i,
                "volume": 1000000
            }
            for i in range(1, 61)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_all_indicators(data)
        
        # Assert
        assert "ma" in result
        assert "macd" in result
        assert "rsi" in result
        assert "kdj" in result
        
        # 驗證 MA 包含多個週期
        assert "ma5" in result["ma"]
        assert "ma10" in result["ma"]
        assert "ma20" in result["ma"]
        
        # 驗證 MACD 包含三條線
        assert "macd" in result["macd"]
        assert "signal" in result["macd"]
        assert "histogram" in result["macd"]
        
        # 驗證 RSI 是列表
        assert isinstance(result["rsi"], list)
        
        # 驗證 KDJ 包含三條線
        assert "k" in result["kdj"]
        assert "d" in result["kdj"]
        assert "j" in result["kdj"]


# ==================== 整合測試場景 ====================

class TestRealWorldScenarios:
    """真實場景測試 - 使用接近實際股市數據"""
    
    def test_volatile_market_scenario(self):
        """場景測試: 劇烈波動市場"""
        # Arrange: 模擬股市劇烈波動
        data = []
        for i in range(60):
            close_price = 100.0 + 10 * np.sin(i * 0.5)  # 波動模式
            data.append({
                "date": f"2024-01-{(i % 30) + 1:02d}",
                "high": close_price + 5,
                "low": close_price - 5,
                "close": close_price
            })
        
        # Act
        result = TechnicalIndicatorService.calculate_all_indicators(data)
        
        # Assert: 所有指標都應該有值，不應崩潰
        assert len(result["ma"]["ma5"]) == 60
        assert len(result["rsi"]) == 60
        assert len(result["kdj"]["k"]) == 60
    
    def test_sideways_market_scenario(self):
        """場景測試: 橫盤整理市場"""
        # Arrange: 價格在窄幅區間波動
        data = [
            {
                "date": f"2024-01-{i:02d}" if i < 32 else f"2024-02-{i-31:02d}",
                "high": 102.0,
                "low": 98.0,
                "close": 100.0 + (i % 3 - 1)  # 在 99, 100, 101 之間波動
            }
            for i in range(1, 61)
        ]
        
        # Act
        result = TechnicalIndicatorService.calculate_all_indicators(data)
        
        # Assert: RSI 應該接近 50 (中性)
        valid_rsi = [x for x in result["rsi"] if x is not None]
        if valid_rsi:
            avg_rsi = np.mean(valid_rsi)
            assert 40 <= avg_rsi <= 60


# ==================== 性能測試 ====================

class TestPerformance:
    """性能測試 - 確保大數據集下性能可接受"""
    
    def test_large_dataset_performance(self):
        """性能測試: 大數據集 (1年 = 250 交易日)"""
        # Arrange
        data = [
            {
                "date": f"2024-{(i//20)+1:02d}-{(i%20)+1:02d}",
                "high": 105.0 + i * 0.1,
                "low": 95.0 + i * 0.1,
                "close": 100.0 + i * 0.1
            }
            for i in range(250)
        ]
        
        # Act
        import time
        start_time = time.time()
        result = TechnicalIndicatorService.calculate_all_indicators(data)
        elapsed_time = time.time() - start_time
        
        # Assert: 應該在 1 秒內完成
        assert elapsed_time < 1.0
        assert len(result["ma"]["ma20"]) == 250


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
