"""
Unit Tests for GeminiService
測試範圍: TR-TC-006 ~ TR-TC-010
Status: ✅ Generated by Sentinel
"""
import pytest
from unittest.mock import Mock, patch, AsyncMock, MagicMock
import json
from backend.apps.core.services.gemini_service import GeminiService


class TestGeminiServiceInitialization:
    """測試 Gemini 服務初始化 - TC-006"""
    
    def test_init_with_api_key(self):
        """TC-006-01: 有 API Key - 應成功初始化"""
        # Arrange & Act
        with patch('google.generativeai.configure') as mock_configure:
            with patch('google.generativeai.GenerativeModel') as mock_model:
                service = GeminiService(api_key="test-api-key")
        
        # Assert
        assert service.is_available() == True
        assert service.api_key == "test-api-key"
        mock_configure.assert_called_once_with(api_key="test-api-key")
    
    def test_init_without_api_key(self):
        """TC-006-02: 無 API Key - 應記錄警告"""
        # Arrange & Act
        with patch.dict('os.environ', {}, clear=True):
            service = GeminiService()
        
        # Assert
        assert service.is_available() == False
        assert service.api_key is None
        assert service.model is None
    
    def test_init_with_env_api_key(self):
        """TC-006-03: 從環境變數讀取 API Key"""
        # Arrange & Act
        with patch.dict('os.environ', {'GEMINI_API_KEY': 'env-api-key'}):
            with patch('google.generativeai.configure'):
                with patch('google.generativeai.GenerativeModel'):
                    service = GeminiService()
        
        # Assert
        assert service.api_key == 'env-api-key'
        assert service.is_available() == True


class TestNewsAnalysis:
    """測試新聞情緒分析 - TC-007"""
    
    @pytest.fixture
    def mock_service(self):
        """建立 Mock 的 Gemini Service"""
        with patch('google.generativeai.configure'):
            with patch('google.generativeai.GenerativeModel'):
                service = GeminiService(api_key="test-key")
                yield service
    
    @pytest.mark.asyncio
    async def test_analyze_positive_news(self, mock_service):
        """TC-007-01: 利多新聞 - 識別為 positive"""
        # Arrange
        mock_response = Mock()
        mock_response.text = '''
```json
{
    "sentiment": "positive",
    "sentiment_score": 0.75,
    "reasoning": "營收成長超出預期"
}
```
'''
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.analyze_news_sentiment(
            title="台積電Q4營收創新高",
            summary="台積電公布Q4營收超出市場預期30%"
        )
        
        # Assert
        assert result["sentiment"] == "positive"
        assert result["sentiment_score"] > 0.3
        assert "營收" in result["reasoning"]
    
    @pytest.mark.asyncio
    async def test_analyze_negative_news(self, mock_service):
        """TC-007-02: 利空新聞 - 識別為 negative"""
        # Arrange
        mock_response = Mock()
        mock_response.text = json.dumps({
            "sentiment": "negative",
            "sentiment_score": -0.65,
            "reasoning": "營收大幅衰退"
        })
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.analyze_news_sentiment(
            title="公司營收衰退",
            summary="Q4營收較去年同期衰退25%"
        )
        
        # Assert
        assert result["sentiment"] == "negative"
        assert result["sentiment_score"] < -0.3
    
    @pytest.mark.asyncio
    async def test_analyze_neutral_news(self, mock_service):
        """TC-007-03: 中性新聞 - 識別為 neutral"""
        # Arrange
        mock_response = Mock()
        mock_response.text = json.dumps({
            "sentiment": "neutral",
            "sentiment_score": 0.05,
            "reasoning": "純數據陳述"
        })
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.analyze_news_sentiment(
            title="收盤價100元",
            summary="今日收盤價100元，成交量1000張"
        )
        
        # Assert
        assert result["sentiment"] == "neutral"
        assert -0.2 <= result["sentiment_score"] <= 0.2
    
    @pytest.mark.asyncio
    async def test_api_failure_fallback(self, mock_service):
        """TC-007-04: API 失敗 - 返回預設中性結果"""
        # Arrange
        mock_service.model.generate_content = Mock(side_effect=Exception("API Error"))
        
        # Act
        result = await mock_service.analyze_news_sentiment(
            title="Test",
            summary="Test summary"
        )
        
        # Assert
        assert result["sentiment"] == "neutral"
        assert result["sentiment_score"] == 0.0
        assert "failed" in result["reasoning"].lower()
    
    @pytest.mark.asyncio
    async def test_service_not_available(self):
        """TC-007-05: 服務不可用 - 返回預設結果"""
        # Arrange
        service = GeminiService(api_key=None)
        
        # Act
        result = await service.analyze_news_sentiment(
            title="Test",
            summary="Test"
        )
        
        # Assert
        assert result["sentiment"] == "neutral"
        assert result["sentiment_score"] == 0.0
        assert "not available" in result["reasoning"]


class TestJSONParsing:
    """測試 JSON 解析 - TC-008"""
    
    @pytest.fixture
    def mock_service(self):
        with patch('google.generativeai.configure'):
            with patch('google.generativeai.GenerativeModel'):
                service = GeminiService(api_key="test-key")
                yield service
    
    @pytest.mark.asyncio
    async def test_parse_json_with_code_block(self, mock_service):
        """TC-008-01: 解析帶 ```json 標記的回應"""
        # Arrange
        mock_response = Mock()
        mock_response.text = '''```json
{"sentiment": "positive", "sentiment_score": 0.8, "reasoning": "Good"}\n```'''
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.analyze_news_sentiment("Title", "Summary")
        
        # Assert
        assert result["sentiment"] == "positive"
        assert result["sentiment_score"] == 0.8
    
    @pytest.mark.asyncio
    async def test_parse_plain_json(self, mock_service):
        """TC-008-02: 解析純 JSON 回應"""
        # Arrange
        mock_response = Mock()
        mock_response.text = '{"sentiment": "negative", "sentiment_score": -0.5, "reasoning": "Bad"}'
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.analyze_news_sentiment("Title", "Summary")
        
        # Assert
        assert result["sentiment"] == "negative"
    
    @pytest.mark.asyncio
    async def test_invalid_json_fallback(self, mock_service):
        """TC-008-03: JSON 格式錯誤 - fallback"""
        # Arrange
        mock_response = Mock()
        mock_response.text = "This is not JSON"
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.analyze_news_sentiment("Title", "Summary")
        
        # Assert
        assert result["sentiment"] == "neutral"
        assert result["sentiment_score"] == 0.0
    
    @pytest.mark.asyncio
    async def test_missing_fields_default_values(self, mock_service):
        """TC-008-04: 缺失欄位 - 使用預設值"""
        # Arrange
        mock_response = Mock()
        mock_response.text = '{"sentiment": "positive"}'
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.analyze_news_sentiment("Title", "Summary")
        
        # Assert
        assert result["sentiment"] == "positive"
        assert result["sentiment_score"] == 0.0  # Default
        assert result["reasoning"] == ""  # Default


class TestScoreValidation:
    """測試分數驗證 - TC-009"""
    
    @pytest.fixture
    def mock_service(self):
        with patch('google.generativeai.configure'):
            with patch('google.generativeai.GenerativeModel'):
                service = GeminiService(api_key="test-key")
                yield service
    
    @pytest.mark.asyncio
    async def test_score_clamped_to_max(self, mock_service):
        """TC-009-01: 分數超過 1.0 - 限制為 1.0"""
        # Arrange
        mock_response = Mock()
        mock_response.text = json.dumps({
            "sentiment": "positive",
            "sentiment_score": 2.5,
            "reasoning": "Test"
        })
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.analyze_news_sentiment("Title", "Summary")
        
        # Assert
        assert result["sentiment_score"] == 1.0
    
    @pytest.mark.asyncio
    async def test_score_clamped_to_min(self, mock_service):
        """TC-009-02: 分數低於 -1.0 - 限制為 -1.0"""
        # Arrange
        mock_response = Mock()
        mock_response.text = json.dumps({
            "sentiment": "negative",
            "sentiment_score": -3.0,
            "reasoning": "Test"
        })
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.analyze_news_sentiment("Title", "Summary")
        
        # Assert
        assert result["sentiment_score"] == -1.0
    
    @pytest.mark.asyncio
    async def test_invalid_sentiment_defaults_to_neutral(self, mock_service):
        """TC-009-03: 無效的 sentiment 值 - 預設為 neutral"""
        # Arrange
        mock_response = Mock()
        mock_response.text = json.dumps({
            "sentiment": "invalid_value",
            "sentiment_score": 0.5,
            "reasoning": "Test"
        })
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.analyze_news_sentiment("Title", "Summary")
        
        # Assert
        assert result["sentiment"] == "neutral"


class TestInvestmentAdvice:
    """測試投資建議生成 - TC-010"""
    
    @pytest.fixture
    def mock_service(self):
        with patch('google.generativeai.configure'):
            with patch('google.generativeai.GenerativeModel'):
                service = GeminiService(api_key="test-key")
                yield service
    
    @pytest.mark.asyncio
    async def test_generate_buy_advice(self, mock_service):
        """TC-010-01: 生成買入建議"""
        # Arrange
        mock_response = Mock()
        mock_response.text = json.dumps({
            "action": "buy",
            "reasoning": "技術指標看好",
            "confidence": 0.8,
            "risk_level": "medium"
        })
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.generate_investment_advice(
            symbol="2330.TW",
            current_price=1050.0,
            indicators={"rsi": 45, "macd": 2.5},
            sentiment="positive"
        )
        
        # Assert
        assert result["action"] == "buy"
        assert 0.0 <= result["confidence"] <= 1.0
        assert result["risk_level"] in ["low", "medium", "high"]
    
    @pytest.mark.asyncio
    async def test_generate_sell_advice(self, mock_service):
        """TC-010-02: 生成賣出建議"""
        # Arrange
        mock_response = Mock()
        mock_response.text = json.dumps({
            "action": "sell",
            "reasoning": "RSI過高",
            "confidence": 0.7,
            "risk_level": "high"
        })
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.generate_investment_advice(
            symbol="AAPL",
            current_price=150.0,
            indicators={"rsi": 75},
            sentiment="negative"
        )
        
        # Assert
        assert result["action"] == "sell"
    
    @pytest.mark.asyncio
    async def test_invalid_action_defaults_to_hold(self, mock_service):
        """TC-010-03: 無效動作 - 預設為 hold"""
        # Arrange
        mock_response = Mock()
        mock_response.text = json.dumps({
            "action": "invalid_action",
            "reasoning": "Test",
            "confidence": 0.5,
            "risk_level": "medium"
        })
        mock_service.model.generate_content = Mock(return_value=mock_response)
        
        # Act
        result = await mock_service.generate_investment_advice(
            symbol="TEST",
            current_price=100.0,
            indicators={},
            sentiment="neutral"
        )
        
        # Assert
        assert result["action"] == "hold"
    
    @pytest.mark.asyncio
    async def test_service_unavailable_advice(self):
        """TC-010-04: 服務不可用 - 返回保守建議"""
        # Arrange
        service = GeminiService(api_key=None)
        
        # Act
        result = await service.generate_investment_advice(
            symbol="TEST",
            current_price=100.0,
            indicators={},
            sentiment="neutral"
        )
        
        # Assert
        assert result["action"] == "hold"
        assert result["confidence"] == 0.0
        assert result["risk_level"] == "unknown"


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
